Ext.onReady(function(){
	var form=new Ext.form.FormPanel({
	title:"",
	labelWidth:80,
	labelAlign:"right",
	layout:"column",
	width:750,
	height:220,
	padding:"5px",
	formId:"queryConsignCompanyForm",
	hideBorders:true,
	frame:true,
	//renderTo:Ext.getBody(),
	buttonAlign:"center",
	monitorValid:true,
	fbar:[
		{
			text:"Save",
			formBind:true,
			handler:mod,
			iconCls:"page_mod"
		},
		{
			text:"Cancel",
			handler:function(){
				closeandreflashEC(true,"consignGrid",false);
			},
			iconCls:"page_cancel"
		}
	],
	items:[
		{
			xtype:"panel",
			title:"",
			columnWidth:0.33,
			layout:"form",
			items:[
				{
					xtype:"hidden",
					fieldLabel:"Company code",
					anchor:"100%",
					id:"companyCode",
					name:"companyCode",
					tabIndex:1
				},{
					xtype:"textfield",
					fieldLabel:"<font color='red'>Shorti Title</font>",
					anchor:"100%",
					allowBlank:false,
					blankText:"Please enter Shorti Title",
					id:"companyName",
					name:"companyName",					
					tabIndex:2
				},
				{
					xtype:"textfield",
					fieldLabel:"Contact",
					anchor:"100%",
					id:"companyContact",
					name:"companyContact",
					tabIndex:4
				},
				{
					xtype:"textfield",
					fieldLabel:"E-mail",
					anchor:"100%",
					id:"companyEmail",
					name:"companyEmail",					
					tabIndex:7
				}
			]
		},
		{
			xtype:"panel",
			title:"",
			columnWidth:0.33,
			layout:"form",
			items:[{
					xtype:"textfield",
					fieldLabel:"<font color='red'>Company</font>",
					id:"companyNameEn",
					name:"companyNameEn",
					allowBlank:false,
					blankText:"Please enter Company",
					anchor:"100%",
					tabIndex:3
				},{
					xtype:"textfield",
					fieldLabel:"Telephone",
					anchor:"100%",
					id:"companyNbr",
					name:"companyNbr",					
					tabIndex:5
				},
				{
					xtype:"textfield",
					fieldLabel:"Address",
					anchor:"100%",
					id:"companyAddr",
					name:"companyAddr",					
					tabIndex:8
				}
			]
		},
		{
			xtype:"panel",
			title:"",
			columnWidth:0.34,
			layout:"form",
			items:[
				{
					xtype:"textfield",
					fieldLabel:"Fax",
					anchor:"100%",
					id:"companyFax",
					name:"companyFax",					
					tabIndex:6
				},
				{
					xtype:"textfield",
					fieldLabel:"Website",
					anchor:"100%",
					id:"companyWebsite",
					name:"companyWebsite",					
					tabIndex:9
				}
			]
		},
		{
			xtype:"panel",
			title:"",
			columnWidth:1,
			layout:"form",
			items:[
				{
					xtype:"textarea",
					fieldLabel:"Booking",
					anchor:"100%",
					id:"companyRemark",
					name:"companyRemark",					
					tabIndex:10
				}
			]
		}
	]
});
	var viewport = new Ext.Viewport({
					layout : 'fit',
					items : [form]
				});
initForm();
});